export const LOGIN = 'LOGIN';

export const SEND_MESSAGE_INIT = 'SEND_MESSAGE_INIT';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';

export const FETCH_MESSAGES_INIT = 'FETCH_MESSAGES_INIT';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAIL = 'FETCH_MESSAGES_FAIL';

export const FETCH_CURRENT_USER_INIT = 'FETCH_CURRENT_USER_INIT';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAIL = 'FETCH_CURRENT_USER_FAIL';

export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
